GoToCinema/GoToCinema/Models/DomainModels/Cinema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GoToCinema.Models.DomainModels
{
    public class Cinema
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Название кинотеатра")]
        public string Name { get; set; }

        [Display(Name = "Изображение")]
        public byte[] Image { get; set; }

        [Display(Name = "Залы кинотеатра")]
        public ICollection<Hall> Halls { get; set; }
    }
}

GoToCinema/GoToCinema/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GoToCinema.Models;
using GoToCinema.Models.DomainModels;
using GoToCinema.Models.DomainModels.Enums;
using Microsoft.AspNet.Identity.Owin;

namespace GoToCinema.Controllers
{
    [Authorize(Roles = "admin")]
    public class CinemasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        [AllowAnonymous]
        public ActionResult Index()
        {
            var cinemas = db.Cinemas.Include(h => h.Halls);
            return View(cinemas);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Cinema cinema, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid && uploadImage != null)
            {
                byte[] imageData = null;

                using(var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }

                cinema.Image = imageData;

                db.Cinemas.Add(cinema);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();

        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var cinema = db.Cinemas.Find(id);
            if (cinema == null)
                return HttpNotFound();
            return View(cinema);
        }

        [AllowAnonymous]
        public ActionResult GetSessionsByDate(int cinemaId, DateTime date)
        {
            var sessions = db.Sessions
                    .Include(x => x.Hall)
                    .Where(x => x.Hall.CinemaId == cinemaId && DbFunctions.TruncateTime(x.Date) == date.Date && x.Date > DateTime.Now)
                    .OrderBy(x => x.Date)
                    .Include(x=>x.Movie)
                    .ToList();

            return PartialView(sessions);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult GetBookingPage(int sessionId)
        {
            var userId = int.Parse(GetUserId((ClaimsPrincipal)User));
            ViewBag.UserId = userId;
            var session = db.Sessions
                        .Include(x=>x.Hall)
                        .Include(x=>x.Movie)
                        .Include(x=>x.Hall.Rows)
                        .Include(x=>x.Hall.Rows.Select(y=>y.Seats))
                        .FirstOrDefault(x=>x.Id == sessionId);
            var sessionSeats = db.SessionSeats.Where(x => x.SessionId == sessionId).ToList();

            var sessionSeatsView = session.Hall.Rows.SelectMany(x => x.Seats.Select(y =>
            {
                var sessionSeat = sessionSeats.FirstOrDefault(z => z.RowId == y.RowId && z.SeatId == y.Id && z.SessionId == sessionId);
                return new SessionSeat
                {
                    RowId = y.RowId,
                    Row = x,
                    SeatId = y.Id,
                    SessionId = sessionId,
                    SeatState = sessionSeat?.SeatState ?? SeatState.Free,
                    UserId = sessionSeat?.UserId ?? null
                };
            })).ToList();

            for (int i = 0; i < sessionSeatsView.Count(); i++)
            {
                var seatId = sessionSeatsView[i].SeatId;
                var sessionSeat = db.SessionSeats.FirstOrDefault(x => x.SessionId == sessionId && x.SeatId == seatId);
                
                if(sessionSeat == null)
                {
                    sessionSeat = sessionSeatsView[i];
                    db.SessionSeats.Add(sessionSeat);
                    db.SaveChanges();
                }
            }

            var bookingModel = new BookingViewModel { SessionSeats = sessionSeatsView };

            ViewBag.Movie = session.Movie.Name;

            return PartialView(bookingModel);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> GetBookingPage(int[] freeSeatIds, int[] bookedSeatIds, int sessionId, SeatAction action)
        {
            int userId = int.Parse(GetUserId((ClaimsPrincipal)User));
            var user = db.Users.Find(userId);
            if(bookedSeatIds != null)
            {
                for(int i = 0; i < bookedSeatIds.Length; i++)
                {
                    var seatId = bookedSeatIds[i];
                    var _sessionSeat = db.SessionSeats.FirstOrDefault(x=>x.SeatId == seatId && x.SessionId == sessionId);
                    if (_sessionSeat != null)
                    {
                        db.SessionSeats.Remove(_sessionSeat);
                        db.SaveChanges();
                    }
                }
            }

            var userSeats = db.SessionSeats.Where(x => x.UserId == userId && x.SessionId == sessionId).Count();
            if (freeSeatIds == null)
                return RedirectToAction("Index");

            if (freeSeatIds.Count()+userSeats > 6)
            {
                var sessionSeats = db.SessionSeats.Where(x => x.SessionId == sessionId).ToList();
                ModelState.AddModelError("", "Купить/Забронировать разрешается не больше шести мест!");
                var bookingViewModel = new BookingViewModel() { SessionSeats = sessionSeats };
                return View();
            }
            
            string text = "";
            if(action == SeatAction.Book)
            {
                for(int i = 0; i < freeSeatIds.Length; i++)
                {
                    int seatId = freeSeatIds[i];
                    var _sessionSeat = db.SessionSeats.Include(x=>x.Row).FirstOrDefault(x => x.SeatId == seatId && x.SessionId == sessionId);
                    _sessionSeat.SeatState = SeatState.Booked;
                    _sessionSeat.UserId = userId;
                    db.Entry(_sessionSeat).State = EntityState.Modified;
                    text = text + $"{_sessionSeat.Row.RowName}{_sessionSeat.Seat.SeatNumber},";
                }
                await UserManager.SendEmailAsync(userId, "GoToCinema", $"Здравствуйте, {user.UserName}. Вы успешно забронировали места {text}");
            }

            if (action == SeatAction.Buy)
            {
                for (int i = 0; i < freeSeatIds.Length; i++)
                {
                    int seatId = freeSeatIds[i];
                    var _sessionSeat = db.SessionSeats.FirstOrDefault(x => x.SeatId == seatId && x.SessionId == sessionId);
                    _sessionSeat.SeatState = SeatState.Bought;
                    _sessionSeat.UserId = userId;
                    db.Entry(_sessionSeat).State = EntityState.Modified;
                    text = text + $"{_sessionSeat.Row.RowName}{_sessionSeat.Seat.SeatNumber},";
                }
                await UserManager.SendEmailAsync(userId, "GoToCinema", $"Здравствуйте, {user.UserName}. Вы успешно купили места {text}");
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var cinema = db.Cinemas.Find(id);
            if (cinema == null)
                return HttpNotFound();

            return View(cinema);
        }

        [HttpPost]
        public ActionResult Edit(Cinema cinema, HttpPostedFileBase uploadImage)
        {
            if (!ModelState.IsValid)
                return View(cinema);
            
            if (uploadImage == null)
            {
                ModelState.AddModelError("", "Загрузите изображение");
                return View(cinema);
            }

            byte[] imageData = null;

            using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            {
                imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            }
            cinema.Image = imageData;
            db.Entry(cinema).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var cinema = db.Cinemas.Find(id);
            if (cinema == null)
                return HttpNotFound();

            return View(cinema);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var cinema = db.Cinemas.Find(id);
            var halls = db.Halls.Where(x => x.CinemaId == cinema.Id).ToList();
            if (halls != null)
            {
                foreach(var hall in halls)
                {
                    var rows = db.Rows.Where(x => x.HallId == hall.Id).ToList();
                    var sessions = db.Sessions.Where(x => x.HallId == hall.Id).ToList();
                    if(sessions != null)
                    {
                        db.Sessions.RemoveRange(sessions);
                    }
                    if (rows != null)
                    {
                        foreach(Row row in rows)
                        {
                            var seats = db.Seats.Where(x => x.RowId == row.Id).ToList();
                            if(seats != null)
                            {
                                foreach(var seat in seats)
                                {

GoToCinema/GoToCinema/Views/Cinemas/Create.cshtml
@model GoToCinema.Models.DomainModels.Cinema

@{
    ViewBag.Title = "Добавление кинотеатра";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="heading">@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Cinemas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="form-group">
                <input type="file" name="uploadImage" />
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-outline-success btn-success" />
            </div>
        </div>
    </div>
    }

    <div class="container-1">
        <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
    </div>

GoToCinema/GoToCinema/Views/Cinemas/Delete.cshtml
@model GoToCinema.Models.DomainModels.Cinema

@{
    ViewBag.Title = "Удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="heading">@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-outline-danger btn-danger"  />
        </div>

        <div class="container-1">
            <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
        </div>
    }
</div>

GoToCinema/GoToCinema/Views/Cinemas/Details.cshtml
@model GoToCinema.Models.DomainModels.Cinema

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="heading">Информация</h2>

<img class="cinemaImage" style="width:900px;height:500px" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Image)" />

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>

@if (User.IsInRole("admin"))
{
    <div style="margin:10px;">
        <a href="/Cinemas/Edit/@Model.Id" class="btn btn-outline-primary">Изменить</a>
        <a href="/Cinemas/Delete/@Model.Id" class="btn btn-outline-danger btn-danger">Удалить</a>
    </div>
    <div class="container-1">
        <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
    </div>
}
else
{
    <div class="container-1">
        <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
    </div>
}

<div style="display: flex;justify-content: center;">
    @for (int i = 0; i < 7; i++)
    {
        using (Ajax.BeginForm("GetSessionsByDate", new AjaxOptions { UpdateTargetId = "result" }))
        {
            <div style="margin:10px;">
                <input type="hidden" name="cinemaId" value="@Model.Id" />
                <input type="submit" name="date" class="btn btn-primary" style="display:inline-block;" value="@DateTime.Now.AddDays(i).ToShortDateString()" />
            </div>
        }
    }
</div>

<div id="result"></div>

GoToCinema/GoToCinema/Views/Cinemas/Edit.cshtml
@model GoToCinema.Models.DomainModels.Cinema

@{
    ViewBag.Title = "Изменение информации ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="heading">@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Cinemas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                <input type="file" name="uploadImage" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-outline-success  btn-success" />
            </div>
        </div>
    </div>
}

<div class="container-1">
    <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
</div>

GoToCinema/GoToCinema/Views/Cinemas/GetBookingPage.cshtml
@using GoToCinema.Models.DomainModels
@using GoToCinema.Models.DomainModels.Enums
@model BookingViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int sessionId = 0;
    string rowName = "";
}
<br />
@Styles.Render("~/Content/MyStyles/BookingPageStyles.css")
<form action="/Cinemas/GetBookingPage" method="post">
    <div class="hall">
        <div>
            @foreach (SessionSeat sessionSeat in Model.SessionSeats)
            {
                if (rowName != sessionSeat.Row.RowName)
                {
                    <br />
                    rowName = sessionSeat.Row.RowName;
                }

                if (sessionSeat.UserId == ViewBag.UserId)
                {
                    if (sessionSeat.SeatState == SeatState.Booked)
                    {
                        <label>
                            <input type="checkbox" class="bookedMe" name="bookedSeatIds" value="@sessionSeat.SeatId" />
                            <span class="fakeBookedMe"></span>
                        </label>
                    }

                    if (sessionSeat.SeatState == SeatState.Bought)
                    {
                        <label>
                            <input type="checkbox" class="boughtMe" />
                            <span class="fakeBoughtMe"></span>
                        </label>
                    }
                }
                else
                {
                    if (sessionSeat.SeatState == SeatState.Bought || sessionSeat.SeatState == SeatState.Booked)
                    {
                        <label>
                            <input type="checkbox" class="busy" />
                            <span class="fakeBusy"></span>
                        </label>
                    }
                    else
                    {
                        <label class="label">

                            @*<input type="hidden" name="@sessionSeat.SeatId" value="@sessionSeat.SeatId" />
                                <input type="hidden" name="@sessionSeat.RowId" value="@sessionSeat.RowId" />
                                <input type="hidden" name="@sessionSeat.SessionId" value="@sessionSeat.SessionId" />
                                <input type="hidden" name="@sessionSeat.UserId" value="@sessionSeat.UserId" />*@
                            <input type="checkbox" class="free" name="freeSeatIds" value="@sessionSeat.SeatId" />
                            <span class="fakeFree"></span>
                        </label>
                    }
                }
                sessionId = sessionSeat.SessionId;
            }
        </div>

        <input type="hidden" name="sessionId" value="@sessionId" />
    </div>
    <div class="screen">
        <div class="fakeScreen"></div>
    </div>
    <div class="btn-group">
        <button type="submit" name="action" class="btn btn-primary" value="@SeatAction.Book">Бронировать</button>
        <button type="submit" name="action" class="btn btn-primary" value="@SeatAction.Buy">Купить</button>
    </div>
    <div class="container-1">
        <a href="/Cinemas/Index" id="backToList" class="btn btn-info">Вернуться на главную</a>
    </div>
</form>

GoToCinema/GoToCinema/Views/Cinemas/GetSessionsByDate.cshtml
@using GoToCinema.Models.DomainModels

@model IEnumerable<Session>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Hall.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movie.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hall.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.ActionLink("Get Booking Page", "GetBookingPage", new { sessionId = item.Id}, new { @class ="btn btn-outline-primary"})
            </td>
        </tr>
    }

</table>

GoToCinema/GoToCinema/Views/Cinemas/Index.cshtml
@model IEnumerable<GoToCinema.Models.DomainModels.Cinema>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/MyStyles/CinemaStyles.css")

@if (User.IsInRole("admin"))
{
    <div>
        <button class="btn btn-outline-primary" onclick="location.href='/Cinemas/Create'" style="margin:10px;">Добавить</button>
    </div>
}

@foreach (var item in Model)
{
    <div class="cinema-item" onclick="location.href = '/Cinemas/Details/@item.Id'">
        <div class="image">
            @if (item.Image != null)
            {
                <img class="cinemaImage" onclick="location.href = '/Cinemas/Details/@item.Id'" src="data:image/jpeg;base64,@Convert.ToBase64String(item.Image)" />
            }
            <h2 class="text-center title"><span class="text-center titleStyle">@item.Name</span></h2>
        </div>
    </div>
}